-- Seeds the real grades table with the same catalog data currently
-- hardcoded in apps/customer/lib/seed-grades.ts, so the app can switch
-- from local seed data to live Supabase queries without the catalog
-- appearing to change. Ported from mvbb-app.jsx DEFAULT_GRADES
-- (prototype lines ~54-64).
insert into grades (
  id, category, label, tagline, description, quality, bulb_size, cloves,
  moisture, shelf_life, origin, export_grade, best_seller, stock_bags, color, tiers
) values
  ('medium', 'Garlic', 'Medium', 'Reliable everyday grade', 'Standard 25–30mm bulbs ideal for retail shops, kitchens and daily cooking. Consistent sizing with good shelf life. Our highest-volume seller across Andhra Pradesh.', 'Standard', '25–30mm', '10–15/bulb', '<65%', '3–4 months', 'Guntur, AP', false, true, 120, '#D4C4B0', '[{"min":1,"price":1450},{"min":5,"price":1380},{"min":10,"price":1320},{"min":25,"price":1260}]'),
  ('maharaja', 'Garlic', 'Maharaja', 'Large bulb, export favourite', 'Premium 35–40mm bulbs with tight skin and bold flavour. Preferred by exporters to Middle East and Southeast Asia. Each bulb hand-sorted for uniform appearance.', 'Premium', '35–40mm', '8–12/bulb', '<60%', '4–5 months', 'Guntur, AP', true, false, 45, '#C9B8A5', '[{"min":1,"price":1650},{"min":5,"price":1560},{"min":10,"price":1490},{"min":25,"price":1410}]'),
  ('skumar', 'Garlic', 'S. Kumar', 'Uniformly graded premium', 'Named after the grading standard, 30–35mm bulbs machine-sorted for perfect uniformity. Ideal for hotel chains and institutional buyers who need consistency.', 'Premium', '30–35mm', '10–14/bulb', '<62%', '4 months', 'Guntur, AP', false, false, 60, '#BFA98F', '[{"min":1,"price":1580},{"min":5,"price":1500},{"min":10,"price":1440},{"min":25,"price":1370}]'),
  ('bom', 'Garlic', 'BOM', 'Bold bulb for kitchens & hotels', 'Bold Off-white Medium — 35mm+ with distinctive white papery skin. High pungency, go-to choice for commercial kitchens, pickles and paste manufacturers.', 'Premium', '35mm+', '8–10/bulb', '<58%', '4–5 months', 'Guntur, AP', true, true, 15, '#A8977F', '[{"min":1,"price":1720},{"min":5,"price":1630},{"min":10,"price":1560},{"min":25,"price":1480}]'),
  ('doublebom', 'Garlic', 'Double BOM', 'Our top-tier export grade', 'Extra bold 40mm+ bulbs — crown jewel of our catalogue. Each bulb individually inspected. Reserved for premium export orders and five-star hotel chains.', 'Super Premium', '40mm+', '6–8/bulb', '<55%', '5–6 months', 'Guntur, AP', true, false, 8, '#9C8B72', '[{"min":1,"price":1890},{"min":5,"price":1790},{"min":10,"price":1710},{"min":25,"price":1620}]'),
  ('kali', 'Garlic', 'KALI', 'Dark-skin, high pungency', 'Dark-skinned variety with intense, sharp flavour profile. Sought after for medicinal preparations, Ayurvedic products and traditional pickle recipes across South India.', 'Specialty', '28–35mm', '12–18/bulb', '<60%', '3–4 months', 'Guntur, AP', false, false, 0, '#7A6B5A', '[{"min":1,"price":1610},{"min":5,"price":1530},{"min":10,"price":1470},{"min":25,"price":1400}]'),
  ('ginger_std', 'Ginger', 'Standard Ginger', 'Handpicked, low-fibre', 'Fresh ginger root sourced from the Guntur region — low fibre, high aroma, everyday cooking grade suited for both home kitchens and commercial use.', 'Standard', 'Medium root', '—', '<70%', '2–3 months', 'Guntur, AP', false, false, 90, '#D9C7A0', '[{"min":1,"price":2100},{"min":5,"price":2000},{"min":10,"price":1920},{"min":25,"price":1840}]'),
  ('onion_medium', 'Onion', 'Medium Onion', 'Everyday red onion, 40–60mm', 'Nashik-grade red onion, medium size — the everyday staple for kitchens and retail. Firm skin, good shelf life, consistent grading.', 'Standard', '40–60mm', '—', '<68%', '2–3 months', 'Kurnool, AP', false, true, 200, '#C97B5E', '[{"min":1,"price":980},{"min":5,"price":930},{"min":10,"price":890},{"min":25,"price":850}]'),
  ('onion_large', 'Onion', 'Large Onion', 'Hotel & catering grade, 60mm+', 'Bold 60mm+ red onion for hotels, caterers and bulk kitchens who need larger, more uniform bulbs for consistent prep.', 'Premium', '60mm+', '—', '<65%', '2–3 months', 'Kurnool, AP', false, false, 35, '#B56A4E', '[{"min":1,"price":1120},{"min":5,"price":1060},{"min":10,"price":1010},{"min":25,"price":970}]')
on conflict (id) do nothing;
